### ISSUE TITLE
Feature request: pls allow for single-connection apps / pushes to multiple topics

### ISSUE THREAD

**Issue by jf** [wistia/nsq-ruby#13]
I'm coding an app now, and suddenly realizing that using `nsq-ruby`, I need to create multiple connections to the same nsqd for _each_ topic that I want to push to. Looking at the official go client (https://godoc.org/github.com/nsqio/go-nsq#Publish), I'm concluding that this isn't a requirement (that 1 connection can only be dedicated to 1 topic), so is it possible to make the following possible?

1. remove necessity to specify topic for `Nsq::Producer.new`
2. make it possible to specify a topic when doing a `write`

Thanks.

**Comment by bschwartz** [comment]
Hey @jf. You're 100% right about that. It's a fairly easy change to make, I'm just unsure of what the best syntax will be for publishing messages to various topics.

Right now it's just:

```ruby
producer = Nsq::Producer.new(nsqd: '127.0.0.1:4150', topic: 'some-topic')
producer.write('some-message')
producer.write('one', 'two', 'three', 'four', 'five')
```

So, we could not specify a topic when creating a new producer instance and then specify it when we call write. What do you think of this syntax?

```ruby
producer.write_to_topic('topic-a', 'some-message')
producer.write_to_topic('topic-b', 'one', 'two', 'three', 'four', 'five')
```

I can't see how we can change `#write` without it being a breaking change, so maybe we add a new method like this? Feels a bit verbose though. Any other ideas?

**Comment by jf** [comment]
I was initially thinking of using an optional argument to specify the topic, but if `write` is going to be multiple-argument, I think that may not work out very nicely in the sense that the code won't be as elegant (we'll need code to detect whether an argument is a symbol ("`:sometopic`"), and then handle it differently). Having said that, I realize that this may be being a bit too perfectionistic.

So one possibility would be to write to the default topic that the producer was set up with if no topic is specified; and then IF a topic is specified, "switch" to that topic and write to that instead. One interesting thing if we were to handle the arguments this way: this would allow for the following use-cases (although I wonder if anybody would really use it that way!):

`producer.write('messages', 'for', 'the', 'standard', 'topic', :topic2, 'messages', 'for', 'topic', '2')`
`producer.write(:topic1, 'message1', 'message2', 'message3', :topic2, 'messages', 'for', 'topic', '2')`

The pro for doing things this way: no breaking changes to `#write`

**Comment by MaxPower15** [comment]
Another idea for a non-breaking syntax is specifying the topic as part of each message. Then we could pivot on the argument type, e.g.

    producer.write({ topic: 'topic-a', message: 'message1' }, { topic: 'topic-b', message: 'message2' })

Specifying a String instead of a Hash would use the default topic.

**Comment by jf** [comment]
That's also possible, although doing this would basically create the situation where multiple producers are actually encouraged, rather than to allow for a true "multi-topic producer" because trying to send to a different topic than the one which the producer was set up with would require so much typing.

**Comment by bschwartz** [comment]
@jf I do love shorter methods :)

Even though it's a rare case, what you proposed with the symbols is technically a breaking change. Right now we call `.to_s` on all args to `#write`, so if someone is sending messages as symbols this would break for them. Again, I think it's unlikely, but felt best to be really clear and explicit. Let me know what you think about the PR and I'll merge it and push the new gem version.

**Comment by jf** [comment]
I see. Didn't know about the `to_s`, argh. I'm ok with `write_to_topic`! Thanks. I'm assuming, btw, that the topic can be given as a symbol?

**Comment by bschwartz** [comment]
@jf Ok, all set here. Also pushed a new version of the gem (1.3.0): https://rubygems.org/gems/nsq-ruby
Thanks for writing in about this!

**Comment by jf** [comment]
:) Sure!
