### ISSUE TITLE
typo in README? "Producing to all nsqd instances automatically via nsqlookupd"

### ISSUE THREAD

**Issue by jf** [wistia/nsq-ruby#16]
Should this be "**consuming from** all nsqd instances automatically via nsqlookupd" instead?

**Comment by bschwartz** [comment]
It's not a typo -- it supports both consuming and producing to all nsqd instances automatically via nsqlookupd. See: https://github.com/wistia/nsq-ruby/pull/6

**Comment by jf** [comment]
Got it. I was confused because I had the example code of the consumer in mind. Technically then, it should be "producing to and consuming from all nsqd instances ..."?
