### ISSUE TITLE
just TLS v1

### ISSUE THREAD

**Issue by mschneider82** [wistia/nsq-ruby#24]
Any plays to support tls_v1 client also?

The current implemenation only supports client certificate validation (AUTH) which requires keys on the nsq client. I just want to encrypt the connection channel.

**Comment by freerobby** [comment]
@mschneider82 We do support tls_v1 as of https://github.com/wistia/nsq-ruby/pull/22/files. We don't have plans to support tls_v1 without keys or certificates on the client, though. Could you explain how you envision that working? Is the idea to generate them on the fly if not provided?

**Comment by mschneider82** [comment]
Hi freerobby,

It works like browsing to a https website, only the webserver (nsqd) has a configured private/certificate. 

thanks @alieander !
