### ISSUE TITLE
nsqlookup failure causes all producers to be removed from set

### ISSUE THREAD

**Issue by bschwartz** [wistia/nsq-ruby#9]
If the read from the nsqlookups fails for some reason (like network something or other), we remove all producers from our set. This causes all NSQ writes to hard fail for a minute until the nsqlookup loop triggers again.

We should better handle this error case and not remove all the producers from the set. Or if we do end up removing them, maybe tighten that loop until we get one back?

**Comment by mreiferson** [comment]
The way `pynsq` and `go-nsq` rely on the combination of disconnections + recurring lookupd queries to keep the list up to date.

Basically, when configured with lookupd, we don't automatically reconnect when connections close.  The periodic lookupd query re-discovers disconnected nodes that are still valid and reconnects.

**Comment by bschwartz** [comment]
@mreiferson Thanks for the reply. That's the way `nsq-ruby` works too and that works fine for consumers. We also added support to give a producer an nsqlookupd address (or addresses) and have it round-robin messages to all your nsqd instances. The issue is that if there's a network partition or failure that causes the lookupd discover loop to fail, we eject all the nsqd's from the pool and so all writes for that producer would fail.

@phopkins pointed out to me that it would be better to leave those nsqds in the pool for this specific failure case as there's a chance some of those writes would succeed. For example, imagine if your nsqlookup process died all of a sudden, but your nsqd's were online. If you don't remove them all from the pool, you could still write to them.

Does that make sense? Maybe I'm missing something.

**Comment by mreiferson** [comment]
Yea, I think taking the approach that you never *remove* things from the list based on any failure or response from `nsqlookupd` is the way to go.

i.e. only ever rely on disconnection + future lack of re-discovery to "remove" a node from the list

**Comment by bschwartz** [comment]
Ok, cool. I'll do that! Thanks Matt.

**Comment by phopkins** [comment]
I'd recommend removing a queue if a successful lookup says it's not there
anymore. Having a failure remove everything is all that seems problematic.

**Comment by bschwartz** [comment]
Sounds good @phopkins. That makes sense to me. Will implement that shortly!
